package inaki.sw.calc.view.swing;

import inaki.sw.calc.controller.Controller;
import inaki.sw.calc.view.IMainView;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author inaki
 * @version 1.1.1
 * @since 1.0
 */
public class MainView extends javax.swing.JFrame implements IMainView {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTop = new javax.swing.JPanel();
        jtfTop = new javax.swing.JTextField();
        jtfOp = new javax.swing.JTextField();
        jtfMain = new javax.swing.JTextField();
        jpMain = new javax.swing.JPanel();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jbPow = new javax.swing.JButton();
        jbPlusMinus = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jbMultiply = new javax.swing.JButton();
        jbDivide = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jbAdd = new javax.swing.JButton();
        jbSubstract = new javax.swing.JButton();
        jbEmpty = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbDot = new javax.swing.JButton();
        jbBackSpace = new javax.swing.JButton();
        jbEqual = new javax.swing.JButton();
        jpBottom = new javax.swing.JPanel();
        jlVersion = new javax.swing.JLabel();
        jbQuit = new javax.swing.JButton();
        jbAns = new javax.swing.JButton();
        jbClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/inaki/sw/calc/icon/isw-calc-96.png")).getImage());

        jtfTop.setEditable(false);
        jtfTop.setBackground(new java.awt.Color(255, 255, 255));
        jtfTop.setFocusable(false);
        jtfTop.setPreferredSize(new java.awt.Dimension(64, 40));

        jtfOp.setEditable(false);
        jtfOp.setBackground(new java.awt.Color(170, 255, 170));
        jtfOp.setColumns(1);
        jtfOp.setFocusable(false);

        jtfMain.setEditable(false);
        jtfMain.setBackground(new java.awt.Color(255, 255, 255));
        jtfMain.setFocusable(false);
        jtfMain.setPreferredSize(new java.awt.Dimension(64, 40));

        javax.swing.GroupLayout jpTopLayout = new javax.swing.GroupLayout(jpTop);
        jpTop.setLayout(jpTopLayout);
        jpTopLayout.setHorizontalGroup(
            jpTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpTopLayout.createSequentialGroup()
                        .addComponent(jtfTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpTopLayout.setVerticalGroup(
            jpTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpMain.setLayout(new java.awt.GridLayout(4, 0, 2, 2));

        jb7.setBackground(new java.awt.Color(0, 136, 0));
        jb7.setForeground(new java.awt.Color(255, 255, 255));
        jb7.setText("<html><body><h1>7</h1></body></html>");
        jb7.setBorderPainted(false);
        jb7.setFocusable(false);
        jpMain.add(jb7);

        jb8.setBackground(new java.awt.Color(0, 136, 0));
        jb8.setForeground(new java.awt.Color(255, 255, 255));
        jb8.setText("<html><body><h1>8</h1></body></html>");
        jb8.setBorderPainted(false);
        jb8.setFocusable(false);
        jpMain.add(jb8);

        jb9.setBackground(new java.awt.Color(0, 136, 0));
        jb9.setForeground(new java.awt.Color(255, 255, 255));
        jb9.setText("<html><body><h1>9</h1></body></html>");
        jb9.setFocusable(false);
        jpMain.add(jb9);

        jbPow.setBackground(new java.awt.Color(170, 255, 170));
        jbPow.setText("<html><body><h1>X<sup>y</sup></h1></body></html>");
        jbPow.setBorderPainted(false);
        jbPow.setFocusable(false);
        jpMain.add(jbPow);

        jbPlusMinus.setBackground(new java.awt.Color(170, 255, 170));
        jbPlusMinus.setText("<html><body><h1>+/-</h1></body></html>");
        jbPlusMinus.setBorderPainted(false);
        jbPlusMinus.setFocusable(false);
        jpMain.add(jbPlusMinus);

        jb4.setBackground(new java.awt.Color(0, 136, 0));
        jb4.setForeground(new java.awt.Color(255, 255, 255));
        jb4.setText("<html><body><h1>4</h1></body></html>");
        jb4.setBorderPainted(false);
        jb4.setFocusable(false);
        jpMain.add(jb4);

        jb5.setBackground(new java.awt.Color(0, 136, 0));
        jb5.setForeground(new java.awt.Color(255, 255, 255));
        jb5.setText("<html><body><h1>5</h1></body></html>");
        jb5.setBorderPainted(false);
        jb5.setFocusable(false);
        jpMain.add(jb5);

        jb6.setBackground(new java.awt.Color(0, 136, 0));
        jb6.setForeground(new java.awt.Color(255, 255, 255));
        jb6.setText("<html><body><h1>6</h1></body></html>");
        jb6.setBorderPainted(false);
        jb6.setFocusable(false);
        jpMain.add(jb6);

        jbMultiply.setBackground(new java.awt.Color(170, 255, 170));
        jbMultiply.setText("<html><body><h1>&times;</h1></body></html>");
        jbMultiply.setBorderPainted(false);
        jbMultiply.setFocusable(false);
        jpMain.add(jbMultiply);

        jbDivide.setBackground(new java.awt.Color(170, 255, 170));
        jbDivide.setText("<html><body><h1>&divide;</h1></body></html>");
        jbDivide.setBorderPainted(false);
        jbDivide.setFocusable(false);
        jpMain.add(jbDivide);

        jb1.setBackground(new java.awt.Color(0, 136, 0));
        jb1.setForeground(new java.awt.Color(255, 255, 255));
        jb1.setText("<html><body><h1>1</h1></body></html>");
        jb1.setBorderPainted(false);
        jb1.setFocusable(false);
        jpMain.add(jb1);

        jb2.setBackground(new java.awt.Color(0, 136, 0));
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setText("<html><body><h1>2</h1></body></html>");
        jb2.setBorderPainted(false);
        jb2.setFocusable(false);
        jpMain.add(jb2);

        jb3.setBackground(new java.awt.Color(0, 136, 0));
        jb3.setForeground(new java.awt.Color(255, 255, 255));
        jb3.setText("<html><body><h1>3</h1></body></html>");
        jb3.setBorderPainted(false);
        jb3.setFocusable(false);
        jpMain.add(jb3);

        jbAdd.setBackground(new java.awt.Color(170, 255, 170));
        jbAdd.setText("<html><body><h1>+</h1></body></html>");
        jbAdd.setBorderPainted(false);
        jbAdd.setFocusable(false);
        jpMain.add(jbAdd);

        jbSubstract.setBackground(new java.awt.Color(170, 255, 170));
        jbSubstract.setText("<html><body><h1>-</h1></body></html>");
        jbSubstract.setBorderPainted(false);
        jbSubstract.setFocusable(false);
        jpMain.add(jbSubstract);

        jbEmpty.setBackground(new java.awt.Color(0, 136, 0));
        jbEmpty.setForeground(new java.awt.Color(255, 255, 255));
        jbEmpty.setBorderPainted(false);
        jbEmpty.setFocusable(false);
        jpMain.add(jbEmpty);

        jb0.setBackground(new java.awt.Color(0, 136, 0));
        jb0.setForeground(new java.awt.Color(255, 255, 255));
        jb0.setText("<html><body><h1>0</h1></body></html>");
        jb0.setBorderPainted(false);
        jb0.setFocusable(false);
        jpMain.add(jb0);

        jbDot.setBackground(new java.awt.Color(0, 136, 0));
        jbDot.setForeground(new java.awt.Color(255, 255, 255));
        jbDot.setText("<html><body><h1>.</h1></body></html>");
        jbDot.setBorderPainted(false);
        jbDot.setFocusable(false);
        jpMain.add(jbDot);

        jbBackSpace.setBackground(new java.awt.Color(170, 255, 170));
        jbBackSpace.setText("<html><body><h1>&larr;</h1></body></html>");
        jbBackSpace.setBorderPainted(false);
        jbBackSpace.setFocusable(false);
        jpMain.add(jbBackSpace);

        jbEqual.setBackground(new java.awt.Color(170, 255, 170));
        jbEqual.setText("<html><body><h1>=</h1></body></html>");
        jbEqual.setBorderPainted(false);
        jbEqual.setFocusable(false);
        jpMain.add(jbEqual);

        jpBottom.setBackground(new java.awt.Color(0, 136, 0));

        jlVersion.setBackground(new java.awt.Color(0, 136, 0));
        jlVersion.setForeground(new java.awt.Color(255, 255, 255));
        jlVersion.setText("v");

        jbQuit.setBackground(new java.awt.Color(170, 255, 170));
        jbQuit.setText("<html><body><h2>Quit</h2></body></html>");
        jbQuit.setBorderPainted(false);

        jbAns.setBackground(new java.awt.Color(170, 255, 170));
        jbAns.setText("<html><body><h2>Ans</h2></body></html>");
        jbAns.setBorderPainted(false);

        jbClean.setBackground(new java.awt.Color(170, 255, 170));
        jbClean.setText("<html><body><h2>Clean</h2></body></html>");
        jbClean.setBorderPainted(false);

        javax.swing.GroupLayout jpBottomLayout = new javax.swing.GroupLayout(jpBottom);
        jpBottom.setLayout(jpBottomLayout);
        jpBottomLayout.setHorizontalGroup(
            jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBottomLayout.setVerticalGroup(
            jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlVersion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setController(Controller c) {
        jtfMain.addActionListener(c);
        jtfMain.addKeyListener(c);
        jtfMain.setActionCommand(EQUAL);
        /* NUMBERS */
        jb0.addActionListener(c);
        jb0.setActionCommand(B0);
        jb1.addActionListener(c);
        jb1.setActionCommand(B1);
        jb2.addActionListener(c);
        jb2.setActionCommand(B2);
        jb3.addActionListener(c);
        jb3.setActionCommand(B3);
        jb4.addActionListener(c);
        jb4.setActionCommand(B4);
        jb5.addActionListener(c);
        jb5.setActionCommand(B5);
        jb6.addActionListener(c);
        jb6.setActionCommand(B6);
        jb7.addActionListener(c);
        jb7.setActionCommand(B7);
        jb8.addActionListener(c);
        jb8.setActionCommand(B8);
        jb9.addActionListener(c);
        jb9.setActionCommand(B9);
        jbDot.addActionListener(c);
        jbDot.setActionCommand(DOT);
        /* OPERATORS */
        jbAdd.addActionListener(c);
        jbAdd.setActionCommand(ADD);
        jbSubstract.addActionListener(c);
        jbSubstract.setActionCommand(SUBSTRACT);
        jbMultiply.addActionListener(c);
        jbMultiply.setActionCommand(MULTIPLY);
        jbDivide.addActionListener(c);
        jbDivide.setActionCommand(DIVIDE);
        jbPow.addActionListener(c);
        jbPow.setActionCommand(POW);
        jbPlusMinus.addActionListener(c);
        jbPlusMinus.setActionCommand(PLUS_MINUS);
        jbBackSpace.addActionListener(c);
        jbBackSpace.setActionCommand(BACKSPACE);
        jbEqual.addActionListener(c);
        jbEqual.setActionCommand(EQUAL);
        /* ACTIONS */
        jbQuit.addActionListener(c);
        jbQuit.setActionCommand(QUIT);
        jbAns.addActionListener(c);
        jbAns.setActionCommand(ANS);
        jbClean.addActionListener(c);
        jbClean.setActionCommand(CLEAN);
    }

    @Override
    public void startView() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            // empty
        } finally {
            this.pack();
        }
        //</editor-fold>

        this.clear();
        this.setVisible(true);
    }

    @Override
    public void clear() {
        jtfTop.setText("");
        jtfOp.setText("");
        jtfMain.setText(B0);
    }

    @Override
    public String getTopText() {
        return jtfTop.getText();
    }

    @Override
    public void setTopText(String s) {
        jtfTop.setText(s);
    }

    @Override
    public String getOpText() {
        return jtfOp.getText();
    }

    @Override
    public void setOpText(String s) {
        jtfOp.setText(s);
    }

    @Override
    public String getMainText() {
        return jtfMain.getText();
    }

    @Override
    public void setMainText(String s) {
        jtfMain.setText(s);
    }

    @Override
    public void setAnsEnabled(boolean b) {
        jbAns.setEnabled(b);
    }

    @Override
    public void setVersion(String version) {
        if (version == null) {
            this.jlVersion.setVisible(false);
        } else {
            this.jlVersion.setVisible(true);
            this.jlVersion.setText(version);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbAns;
    private javax.swing.JButton jbBackSpace;
    private javax.swing.JButton jbClean;
    private javax.swing.JButton jbDivide;
    private javax.swing.JButton jbDot;
    private javax.swing.JButton jbEmpty;
    private javax.swing.JButton jbEqual;
    private javax.swing.JButton jbMultiply;
    private javax.swing.JButton jbPlusMinus;
    private javax.swing.JButton jbPow;
    private javax.swing.JButton jbQuit;
    private javax.swing.JButton jbSubstract;
    private javax.swing.JLabel jlVersion;
    private javax.swing.JPanel jpBottom;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpTop;
    private javax.swing.JTextField jtfMain;
    private javax.swing.JTextField jtfOp;
    private javax.swing.JTextField jtfTop;
    // End of variables declaration//GEN-END:variables
}
