package inaki.sw.calc.view.swing;

import inaki.sw.calc.controller.Controller;
import inaki.sw.calc.view.IPreferencesView;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author inaki
 */
public class PreferencesView extends javax.swing.JDialog implements IPreferencesView {

    private final javax.swing.ComboBoxModel languageModel = new javax.swing.DefaultComboBoxModel(new String[]{"<html><body><h3>English</h3></body></html>"});
    private final javax.swing.ComboBoxModel appearanceModel = new javax.swing.DefaultComboBoxModel(new String[]{"<html><body><h3>Green</h3></body></html>"});

    /**
     * Creates new form PreferencesView
     *
     * @param parent
     * @param modal
     */
    public PreferencesView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLanguage = new javax.swing.JPanel();
        jcbLanguage = new javax.swing.JComboBox<>();
        jpAppearance = new javax.swing.JPanel();
        jcbAppearance = new javax.swing.JComboBox<>();
        jpBottom = new javax.swing.JPanel();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ISW Calculator - Preferences");

        jpLanguage.setBackground(new java.awt.Color(170, 255, 170));
        jpLanguage.setBorder(javax.swing.BorderFactory.createTitledBorder("<html><body><h2>Language</h2></body></html>"));

        jcbLanguage.setModel(languageModel);
        jcbLanguage.setFocusable(false);

        javax.swing.GroupLayout jpLanguageLayout = new javax.swing.GroupLayout(jpLanguage);
        jpLanguage.setLayout(jpLanguageLayout);
        jpLanguageLayout.setHorizontalGroup(
            jpLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbLanguage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLanguageLayout.setVerticalGroup(
            jpLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpAppearance.setBackground(new java.awt.Color(170, 255, 170));
        jpAppearance.setBorder(javax.swing.BorderFactory.createTitledBorder("<html><body><h2>Appearance</h2></body></html>"));

        jcbAppearance.setModel(appearanceModel);
        jcbAppearance.setFocusable(false);

        javax.swing.GroupLayout jpAppearanceLayout = new javax.swing.GroupLayout(jpAppearance);
        jpAppearance.setLayout(jpAppearanceLayout);
        jpAppearanceLayout.setHorizontalGroup(
            jpAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbAppearance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpAppearanceLayout.setVerticalGroup(
            jpAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpBottom.setBackground(new java.awt.Color(0, 136, 0));

        jbOK.setBackground(new java.awt.Color(170, 255, 170));
        jbOK.setText("<html><body><h2>OK</h2></body></html>");
        jbOK.setBorderPainted(false);

        jbCancel.setBackground(new java.awt.Color(170, 255, 170));
        jbCancel.setText("<html><body><h2>Cancel</h2></body></html>");
        jbCancel.setBorderPainted(false);

        javax.swing.GroupLayout jpBottomLayout = new javax.swing.GroupLayout(jpBottom);
        jpBottom.setLayout(jpBottomLayout);
        jpBottomLayout.setHorizontalGroup(
            jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBottomLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBottomLayout.setVerticalGroup(
            jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAppearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAppearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setController(Controller c) {
        jbOK.addActionListener(c);
        jbOK.setActionCommand(PV_OK);
        jbCancel.addActionListener(c);
        jbCancel.setActionCommand(PV_CANCEL);
    }

    @Override
    public void startView() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            // empty
        } finally {
            this.pack();
        }
        //</editor-fold>

        this.setVisible(true);
    }

    @Override
    public void close() {
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JComboBox<String> jcbAppearance;
    private javax.swing.JComboBox<String> jcbLanguage;
    private javax.swing.JPanel jpAppearance;
    private javax.swing.JPanel jpBottom;
    private javax.swing.JPanel jpLanguage;
    // End of variables declaration//GEN-END:variables
}
